# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.00) in your motion requests.  # Increase the values below to 1.00 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 200.00
    has_acceleration_limits: false
    max_acceleration: 0.0 
  joint2:
    has_velocity_limits: true
    max_velocity: 200.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  joint_link1_link2:
    has_velocity_limits: true
    max_velocity: 200.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  joint_link1_link2_intermediate:
    has_velocity_limits: true
    max_velocity: 200.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  passive_joint4_mimic:
    has_velocity_limits: true
    max_velocity: 200.00
    has_acceleration_limits: false
    max_acceleration: 0.00
